[anthropic]
api_key = "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"

[greptile]
api_key = "uwfpO9HQ/i68vqAUqTuvdCjq/mzgUuCgXl9mEysJiYJOe3dp"
